# Generated by Django 5.0.4 on 2026-04-22 15:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchlistAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('previous_price', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('new_price', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name='watchlistasset',
            constraint=models.CheckConstraint(check=models.Q(('current_price__gt', 0)), name='current_price_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='watchlistasset',
            constraint=models.CheckConstraint(check=models.Q(('target_price__gt', 0)), name='target_price_gt_zero'),
        ),
        migrations.AddField(
            model_name='watchlistauditlog',
            name='asset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='watchlist.watchlistasset'),
        ),
    ]
